language: ruby
os: osx
osx_image: xcode9.4

env:
  - R_LIBS_USER=~/R

cache:
  directories:
    - $HOME/R

before_install:
  - mkdir -p ~/R
  - mkdir -p ~/.R

install:
  - brew cask install r-app gfortran xquartz
  - brew tap r-hub/cran
  - brew install autobrew
  - brew tap homebrew/cask-drivers

script:
  - export PATH=/usr/local/opt/qt/bin:$PATH
  - ./build.sh
