language: ruby
os: osx
osx_image: xcode12

env:
  - R_LIBS_USER=~/R

cache:
  directories:
    - $HOME/R

before_install:
  - mkdir -p ~/R
  - mkdir -p ~/.R

install:
  - brew update
  - brew cask install r gfortran xquartz
  - brew tap r-hub/cran
  - brew install autobrew

script:
  - export PATH=/usr/local/opt/qt/bin:$PATH
  - ./build.sh
