language: ruby
os: osx
osx_image: xcode9.3

cache:
  directories:
    - $HOME/R

before_install:
  - mkdir -p ~/R

install:
  - brew install gcc || true
  - brew link --overwrite gcc
  - brew install r

script:
  - Rscript build.R
