language: ruby
os: osx
osx_image: xcode9.3

env:
  - R_LIBS_USER=~/R

cache:
  directories:
    - $HOME/R

before_install:
  - mkdir -p ~/R

install:
  - brew cask install r-app gfortran
  - brew cask reinstall xquartz
  - brew tap r-hub/cran
  - brew install autobrew

script:
  - ./build.sh
